# Generated by Django 3.0.6 on 2020-05-17 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200517_0325'),
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='products',
            field=models.ManyToManyField(related_name='wishlists', to='product.Product'),
        ),
        migrations.DeleteModel(
            name='WishlistItem',
        ),
    ]
