# Generated by Django 3.0.6 on 2020-05-17 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='invoice',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='invoice.Invoice'),
            preserve_default=False,
        ),
    ]
