# Generated by Django 3.0.6 on 2020-05-31 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleryitem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryitem',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='uploads/gallery/'),
        ),
    ]
