# Generated by Django 3.0.6 on 2020-05-17 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='detail',
            new_name='details',
        ),
    ]
